name: "System: Add Project Entry"

on:
  # Escucha los eventos disparados desde el JavaScript del Dashboard
  repository_dispatch:
    types: [add_project, add_phase, add_task, edit_task] # <-- Agregado edit_task aquí

permissions:
  contents: write

jobs:
  update-system:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Se usa el secreto GITOPS_TOKEN configurado en Settings para poder hacer push
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Engine
        # Inyectamos las variables limpias al entorno de Linux de forma independiente
        # Evitamos el error de contexto usando el mapeo nativo directo
        env:
          GITOPS_ACTION: ${{ github.event.action }}
          GITOPS_DATA: ${{ toJson(github.event.client_payload.data) }}
        run: |
          python3 core/manage-projects.py

      - name: Sync Changes
        run: |
          git config --global user.name "System-Bot"
          git config --global user.email "bot@system.local"
          git add _data/project-schedule.json
          # Cambiado data.name por github.event.action para que el mensaje sirva para cualquier operación (add o edit)
          git diff --quiet && git diff --staged --quiet || (git commit -m "data: remote update [${{ github.event.action }}]" && git push)
